# Generated by Django 4.0.6 on 2022-07-04 22:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0003_alter_recipe_author_alter_recipe_category_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recipe',
            old_name='servings_time_unit',
            new_name='servings_unit',
        ),
    ]
